### ISSUE TITLE
Timeouts when reading

### ISSUE THREAD

**Issue by agentgonzo** [petervojtek/usb-thermometer#7]
I've got a TEMPer USB device (TEMPer1F_V1.3) running on Centos. I cloned your code and ran it, but am having odd timeout behaviour. The first time it runs, it works fine (if I just run it once or in a loop, everything is as expected), but the process exits and I run it again I just get timeouts when reading from the USB device:
USB interrupt read: Connection timed out

It seems to be sending the control message fine, but timesout when it tries to read from the USB as if there is no data to read. Any ideas why this could happen? I've not done any USB development but read through the code and it seemed to be OK. All return values from closing the interfaces and USB device from the previous run were 0 (success) so it seemed to close down OK, but the next time it runs I get the timeout. Any help would be appreciated!

**Comment by petervojtek** [comment]
hi, I experienced somehow similiar behaviour when using TEMPer (v1.2) from Raspbian - in such case every 13th read of the temperature failed with "Resource temporarily unavailable" (the other 12 reads were successful). 

I did not managed to inspect the root of the problem - in my case it was sufficient to just read the temperature once again when the error occured.

**Comment by agentgonzo** [comment]
Yep, I just disabled the exit in the bad function and got it to re read
from the USB and it worked fine! Thanks
